export const appConstant = {
 welcome: 'Welcome Back',
 welcomeDescription: 'Sign in with your email and password or continue with social media',
 email: 'Email',
 password: 'Password',
 rememberMe: 'Remember me',
 forgotPassword: 'Forgot Password?',
 logIn: 'Log In',
 search: 'Search',
 sms: 'Sms',
 profile: 'Profile',
 orLogIn: 'Or Login With...',
 dontAccount: 'Don’t have an account? ',
 signUp: 'SIGN UP',
 TopCategories : 'Top Categories',
 SeeAll: 'See All',
 PopularCourses: 'Popular Courses',
 TreadingCourses: 'Treading Courses',
 emailError: 'please enter valid email',
 passwordError: 'please enter valid password',
 locationHome: 'Avenida de Carlos III el Noble, 5',
searchHome: 'Search...',
};
